<?php

/**
 * Implements hook_ctools_plugin_type().
 */
function doc_search_ctools_plugin_type() {
  return array(
    'doc_search_providers' => array(
      'use hooks' => TRUE,
    ),
    'doc_search_post_alters' => array(
      'use hooks' => TRUE,
      'info file' => TRUE,
      'defaults'  => array(
        'weight'  => 0,
      ),
    ),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function doc_search_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}
